//! End-to-end tests for the clinical-safety gates.
//!
//! These exercise the real conversion pipeline (`convert_dtc_file`) and assert
//! that malformed / empty / sparse / unparseable inputs now fail loud with a
//! nonzero `Err` instead of silently exiting 0 with empty or mis-parsed output.
//!
//! To stay offline and deterministic, every config sets `input_build` so the
//! network-dependent position-based build detection is skipped; the
//! build-confidence gate itself is covered by the unit tests in `conversion.rs`.

use std::path::PathBuf;

use assert_fs::{TempDir, prelude::*};
use convert_genome::{
    ConversionConfig, OutputFormat, convert_dtc_file,
    conversion::{DEFAULT_MAX_PARSE_ERROR_RATIO, DEFAULT_MIN_EMITTED_VARIANTS},
    input::InputFormat,
};

/// A tiny reference covering chr1; enough for the DTC source to validate the
/// handful of positions used in the "valid input" test.
fn write_reference(dir: &TempDir) -> PathBuf {
    let fasta = dir.child("ref.fa");
    // 32 bases on chr1 so positions 1..=32 resolve.
    fasta.write_str(">1\nACGTACGTACGTACGTACGTACGTACGTACGT\n").unwrap();
    fasta.path().to_path_buf()
}

fn config(input: PathBuf, reference: PathBuf, output: PathBuf) -> ConversionConfig {
    ConversionConfig {
        input,
        input_format: InputFormat::Dtc,
        input_origin: "test".into(),
        reference_fasta: Some(reference),
        reference_origin: Some("ref".into()),
        reference_fai: None,
        reference_fai_origin: None,
        output,
        output_dir: None,
        output_format: OutputFormat::Vcf,
        sample_id: "SAMPLE".into(),
        assembly: "GRCh38".into(),
        include_reference_sites: true,
        sex: Some(convert_genome::cli::Sex::Female),
        par_boundaries: None,
        standardize: false,
        panel: None,
        // Skip network-based build detection (offline test).
        input_build: Some("GRCh38".into()),
        min_emitted_variants: DEFAULT_MIN_EMITTED_VARIANTS,
        min_build_confidence: 0.0,
        max_parse_error_ratio: DEFAULT_MAX_PARSE_ERROR_RATIO,
    }
}

fn write_input(dir: &TempDir, name: &str, contents: &str) -> PathBuf {
    let f = dir.child(name);
    f.write_str(contents).unwrap();
    f.path().to_path_buf()
}

fn write_input_bytes(dir: &TempDir, name: &str, bytes: &[u8]) -> PathBuf {
    let f = dir.child(name);
    f.write_binary(bytes).unwrap();
    f.path().to_path_buf()
}

#[test]
fn empty_input_fails_loud() {
    let dir = TempDir::new().unwrap();
    let reference = write_reference(&dir);
    let input = write_input(&dir, "empty.txt", "");
    let output = dir.child("out.vcf").path().to_path_buf();

    let err = convert_dtc_file(config(input, reference, output)).unwrap_err();
    assert!(
        err.to_string().contains("below the minimum"),
        "empty input should fail the min-emitted gate, got: {err}"
    );
}

#[test]
fn header_only_input_fails_loud() {
    let dir = TempDir::new().unwrap();
    let reference = write_reference(&dir);
    // 23andMe-style header comments, but zero data rows.
    let input = write_input(
        &dir,
        "header_only.txt",
        "# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n",
    );
    let output = dir.child("out.vcf").path().to_path_buf();

    let err = convert_dtc_file(config(input, reference, output)).unwrap_err();
    assert!(
        err.to_string().contains("below the minimum"),
        "header-only input should fail the min-emitted gate, got: {err}"
    );
}

#[test]
fn binary_garbage_as_csv_fails_loud() {
    let dir = TempDir::new().unwrap();
    let reference = write_reference(&dir);
    // Non-text bytes dressed up with a .csv name. Read as DTC, nearly every
    // line is unparseable; the result must be an Err, not a near-empty VCF.
    let mut bytes = Vec::new();
    for i in 0u16..4000 {
        bytes.extend_from_slice(&[0x00, 0xFF, (i & 0xFF) as u8, 0x7F, b'\n']);
    }
    let input = write_input_bytes(&dir, "garbage.csv", &bytes);
    let output = dir.child("out.vcf").path().to_path_buf();

    let err = convert_dtc_file(config(input, reference, output)).unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("failed to parse") || msg.contains("below the minimum"),
        "binary garbage should fail a safety gate, got: {msg}"
    );
}

#[test]
fn non_genome_csv_fails_loud() {
    let dir = TempDir::new().unwrap();
    let reference = write_reference(&dir);
    // A perfectly valid 4-column CSV that is NOT a genome (e.g. an export of
    // some unrelated table). Misread as rsid,chr,pos,genotype it must not
    // silently produce a sparse result.
    let mut rows = String::from("name,city,age,note\n");
    for i in 0..3000 {
        rows.push_str(&format!("Alice{i},Boston,{},hello\n", 20 + (i % 50)));
    }
    let input = write_input(&dir, "table.csv", &rows);
    let output = dir.child("out.vcf").path().to_path_buf();

    let err = convert_dtc_file(config(input, reference, output)).unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("failed to parse") || msg.contains("below the minimum"),
        "non-genome CSV should fail a safety gate, got: {msg}"
    );
}

#[test]
fn small_valid_input_passes_when_gate_is_relaxed() {
    // A small but genuine DTC file converts cleanly once the floor is set to a
    // value appropriate for a tiny test panel. This proves the gates do not
    // reject real (if small) genomic data, only empty/malformed input.
    let dir = TempDir::new().unwrap();
    let reference = write_reference(&dir);
    let mut rows = String::from("# rsid\tchromosome\tposition\tgenotype\n");
    for pos in 1u64..=20 {
        rows.push_str(&format!("rs{pos}\t1\t{pos}\tAA\n"));
    }
    let input = write_input(&dir, "small.txt", &rows);
    let output = dir.child("out.vcf").path().to_path_buf();

    let mut cfg = config(input, reference, output.clone());
    cfg.min_emitted_variants = 1; // accept a tiny panel
    let summary = convert_dtc_file(cfg).expect("small valid input should convert cleanly");
    assert!(summary.emitted_records > 0, "expected some emitted records");
    assert!(output.exists(), "expected an output VCF to be written");
}

#[test]
fn small_valid_input_fails_under_production_floor() {
    // The same small file fails under the production default floor: a 20-site
    // panel is far below what a real genome/array yields, so it is rejected.
    let dir = TempDir::new().unwrap();
    let reference = write_reference(&dir);
    let mut rows = String::from("# rsid\tchromosome\tposition\tgenotype\n");
    for pos in 1u64..=20 {
        rows.push_str(&format!("rs{pos}\t1\t{pos}\tAA\n"));
    }
    let input = write_input(&dir, "small.txt", &rows);
    let output = dir.child("out.vcf").path().to_path_buf();

    let err = convert_dtc_file(config(input, reference, output)).unwrap_err();
    assert!(
        err.to_string().contains("below the minimum"),
        "20-site panel should fail the default floor, got: {err}"
    );
}
